kind: PrometheusRule
apiVersion: monitoring.coreos.com/v1
metadata:
  name: kube-high-network-drops-normalised
  namespace: messaging
spec:
  groups:
  - name: kube-node-alerts
    rules:
    - alert: KubeHighNetworkDropsNormalised
      expr: |
        (sum(increase(node_network_receive_drop_total[5m])) + sum(increase(node_network_transmit_drop_total[5m]))) / (sum(increase(node_network_receive_bytes_total[5m])) / 8 + sum(increase(node_network_transmit_bytes_total[5m])) / 8) > 0.05 # Convert bytes to bits
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "High network drop rate on node {{ $labels.instance }}"
        description: "Node {{ $labels.instance }} is experiencing a network drop rate exceeding 5%. Investigate for potential congestion, hardware issues, or configuration errors."
