kind: PrometheusRule
apiVersion: monitoring.coreos.com/v1
metadata:
  name: kube-deployment-generation-mismatch
  namespace: messaging
spec:
  groups:
  - name: kube-node-alerts
    rules:
    - alert: KubeDeploymentGenerationMismatch
      expr: |
        kube_deployment_status_observed_generation{job="kube-state-metrics"}
        !=
        kube_deployment_metadata_generation{job="kube-state-metrics"}
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: Deployment generation for {{ $labels.namespace }}/{{ $labels.deployment }} does not match, this indicates that the Deployment has failed but has not been rolled back.
        description: Deployment generation mismatch due to possible roll-back
