kind: PrometheusRule
apiVersion: monitoring.coreos.com/v1
metadata:
  name: kube-quota-exceeded
  namespace: messaging
spec:
  groups:
  - name: kube-node-alerts
    rules:
    - alert: KubeQuotaExceeded
      expr: |
        kube_resourcequota{job="kube-state-metrics", type="used"}
        / ignoring(instance, job, type)
        (kube_resourcequota{job="kube-state-metrics", type="hard"} > 0)
        > 1
      for: 15m
      labels:
        severity: warning
      annotations:
        description: Namespace {{ $labels.namespace }} is using {{ $value | humanizePercentage }} of its {{ $labels.resource }} quota.
        summary: Namespace quota has exceeded the limits.
