kind: PrometheusRule
apiVersion: monitoring.coreos.com/v1
metadata:
  name: kube-cpu-overcommit
  namespace: messaging
spec:
  groups:
  - name: kube-node-alerts
    rules:
    - alert: KubeCPUOvercommit
      expr: |
        sum(namespace_cpu:kube_pod_container_resource_requests:sum{}) - (sum(kube_node_status_allocatable{resource="cpu", job="kube-state-metrics"}) - max(kube_node_status_allocatable{resource="cpu", job="kube-state-metrics"})) > 0
        and
        (sum(kube_node_status_allocatable{resource="cpu", job="kube-state-metrics"}) - max(kube_node_status_allocatable{resource="cpu", job="kube-state-metrics"})) > 0
      for: 10m
      labels:
        severity: warning
      annotations:
        description: Cluster has overcommitted CPU resource requests for Pods by {{ $value }} CPU shares and cannot tolerate node failure.
        summary: Cluster has overcommitted CPU resource requests.
