kind: PrometheusRule
apiVersion: monitoring.coreos.com/v1
metadata:
  name: kube-persistent-volume-filling-up-warning
  namespace: messaging
spec:
  groups:
  - name: kube-node-alerts
    rules:
    - alert: KubePersistentVolumeFillingUpWarning
      expr: |
        (
          kubelet_volume_stats_available_bytes{job="kubelet"}
            /
          kubelet_volume_stats_capacity_bytes{job="kubelet"}
        ) < 0.15
        and
        kubelet_volume_stats_used_bytes{job="kubelet"} > 0
        and
        predict_linear(kubelet_volume_stats_available_bytes{job="kubelet"}[6h], 4 * 24 * 3600) < 0
        unless on(namespace, persistentvolumeclaim)
        kube_persistentvolumeclaim_access_mode{ access_mode="ReadOnlyMany"} == 1
        unless on(namespace, persistentvolumeclaim)
        kube_persistentvolumeclaim_labels{label_excluded_from_alerts="true"} == 1
      for: 1h
      labels:
        severity: warning
      annotations:
        description: The PersistentVolume claimed by {{ $labels.persistentvolumeclaim }} in Namespace {{ $labels.namespace }} is only {{ $value | humanizePercentage }} free.
        summary: PersistentVolume is filling up.
---
kind: PrometheusRule
apiVersion: monitoring.coreos.com/v1
metadata:
  name: kube-persistent-volume-filling-up-critical
spec:
  groups:
  - name: kube-node-alerts
    rules:
    - alert: KubePersistentVolumeFillingUpCritical
      expr: |
        (
        kubelet_volume_stats_available_bytes{job="kubelet"}
        /
        kubelet_volume_stats_capacity_bytes{job="kubelet"}
        ) < 0.03
        and
        kubelet_volume_stats_used_bytes{job="kubelet"} > 0
        unless on(namespace, persistentvolumeclaim)
        kube_persistentvolumeclaim_access_mode{ access_mode="ReadOnlyMany"} == 1
        unless on(namespace, persistentvolumeclaim)
        kube_persistentvolumeclaim_labels{label_excluded_from_alerts="true"} == 1
      for: 1m
      labels:
        severity: critical
      annotations:
        description: The PersistentVolume claimed by {{ $labels.persistentvolumeclaim }} in Namespace {{ $labels.namespace }} is only {{ $value | humanizePercentage }} free.
        summary: PersistentVolume is filling up.
