kind: PrometheusRule
apiVersion: monitoring.coreos.com/v1
metadata:
  name: kube-quota-fully-used
  namespace: messaging
spec:
  groups:
  - name: kube-node-alerts
    rules:
    - alert: KubeQuotaFullyUsed
      expr: |
        kube_resourcequota{job="kube-state-metrics", type="used"}
        / ignoring(instance, job, type)
        (kube_resourcequota{job="kube-state-metrics", type="hard"} > 0)
        == 1
      for: 15m
      labels:
        severity: info
      annotations:
        description: Namespace {{ $labels.namespace }} is using {{ $value | humanizePercentage }} of its {{ $labels.resource }} quota
        summary: Namespace quota is fully used.
