kind: PrometheusRule
apiVersion: monitoring.coreos.com/v1
metadata:
  name: kube-unexpected-traffic-drop
  namespace: messaging
spec:
  groups:
  - name: kube-node-alerts
    rules:
    - alert: KubeUnexpectedTrafficDrop
      expr: avg_over_time(node_network_receive_bytes_total[10m]) / avg_over_time(node_network_receive_bytes_total[30m]) < 0.5 # Drop below 50%
      for: 5m
      labels:
        severity: warning
      annotations:
        description: "Network receive traffic has dropped significantly. Check configuration, connectivity, or potential service disruption."
        summary: "Unusual traffic drop on node {{ $labels.instance }}"
