kind: PrometheusRule
apiVersion: monitoring.coreos.com/v1
metadata:
  name: kube-deployment-replicas-mismatch
  namespace: messaging
spec:
  groups:
  - name: kube-node-alerts
    rules:
    - alert: KubeDeploymentReplicasMismatch
      expr: |
        (
          kube_deployment_spec_replicas{job="kube-state-metrics"}
            >
          kube_deployment_status_replicas_available{job="kube-state-metrics"}
        ) and (
        changes(kube_deployment_status_replicas_updated{job="kube-state-metrics"}[10m])
        ==
        0
        )
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: Deployment has not matched the expected number of replicas.
        description: Deployment {{ $labels.namespace }}/{{ $labels.deployment }} has not matched the expected number of replicas for longer than 15 minutes.
