kind: PrometheusRule
apiVersion: monitoring.coreos.com/v1
metadata:
  name: kube-cpu-quota-over-commit
  namespace: messaging
spec:
  groups:
  - name: kube-node-alerts
    rules:
    - alert: KubeCPUQuotaOvercommit
      expr: |
        sum(min without(resource) (kube_resourcequota{job="kube-state-metrics", type="hard", resource=~"(cpu|requests.cpu)"}))
        /
        sum(kube_node_status_allocatable{resource="cpu", job="kube-state-metrics"})
        > 1.5
      for: 5m
      labels:
        severity: warning
      annotations:
        description: Cluster has overcommitted CPU resource requests for Namespaces.
        summary: Cluster has overcommitted CPU resource requests.
