kind: PrometheusRule
apiVersion: monitoring.coreos.com/v1
metadata:
  name: kube-pod-not-ready
  namespace: messaging
spec:
  groups:
  - name: kube-node-alerts
    rules:
    - alert: KubePodNotReady
      expr: |
        sum by (namespace, pod, cluster) (
        max by(namespace, pod, cluster) (
        kube_pod_status_phase{job="kube-state-metrics", phase=~"Pending|Unknown|Failed"}
        ) * on(namespace, pod, cluster) group_left(owner_kind) topk by(namespace, pod, cluster) (
        1, max by(namespace, pod, owner_kind, cluster) (kube_pod_owner{owner_kind!="Job"})
        )
        ) > 0
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: "Pod has been in a non-ready state for more than 15 minutes."
        description: Pod {{ $labels.namespace }}/{{ $labels.pod }} has been in a non-ready state for longer than 15 minutes.

