kind: PrometheusRule
apiVersion: monitoring.coreos.com/v1
metadata:
  name: pod-crashlooping-rules
  namespace: messaging
spec:
  groups:
  - name: kube-node-alerts
    rules:
    - alert: KubePodCrashLooping
      expr: max_over_time(kube_pod_container_status_waiting_reason{reason="CrashLoopBackOff", job="kube-state-metrics"}[5m]) > 1
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: "Pod is crash looping."
        description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} ({{ $labels.container }}) is in waiting state (reason: \"CrashLoopBackOff\")."
