kind: PrometheusRule
apiVersion: monitoring.coreos.com/v1
metadata:
  name: kube-persistent-volume-inodes-filling-up-critical
  namespace: messaging
spec:
  groups:
  - name: kube-node-alerts
    rules:
    - alert: KubePersistentVolumeInodesFillingUpCritical
      expr: |
        (
        kubelet_volume_stats_inodes_free{job="kubelet"}
        /
        kubelet_volume_stats_inodes{job="kubelet"}
        ) < 0.03
        and
        kubelet_volume_stats_inodes_used{job="kubelet"} > 0
        unless on(namespace, persistentvolumeclaim)
        kube_persistentvolumeclaim_access_mode{ access_mode="ReadOnlyMany"} == 1
        unless on(namespace, persistentvolumeclaim)
        kube_persistentvolumeclaim_labels{label_excluded_from_alerts="true"} == 1
      for: 1m
      labels:
        severity: critical
      annotations:
        description: The PersistentVolume claimed by {{ $labels.persistentvolumeclaim }} in Namespace {{ $labels.namespace }} only has {{ $value | humanizePercentage }} free inodes.
        summary: PersistentVolumeInodes are filling up.
---
kind: PrometheusRule
apiVersion: monitoring.coreos.com/v1
metadata:
  name: kube-persistent-volume-inodes-filling-up-warning
spec:
  groups:
  - name: kube-node-alerts
    rules:
    - alert: KubePersistentVolumeInodesFillingUpWarning
      expr: |
        (
        kubelet_volume_stats_inodes_free{job="kubelet"}
        /
        kubelet_volume_stats_inodes{job="kubelet"}
        ) < 0.15
        and
        kubelet_volume_stats_inodes_used{job="kubelet"} > 0
        and
        predict_linear(kubelet_volume_stats_inodes_free{job="kubelet"}[6h], 4 * 24 * 3600) < 0
        unless on(namespace, persistentvolumeclaim)
        kube_persistentvolumeclaim_access_mode{ access_mode="ReadOnlyMany"} == 1
        unless on(namespace, persistentvolumeclaim)
        kube_persistentvolumeclaim_labels{label_excluded_from_alerts="true"} == 1
      for: 1h
      labels:
        severity: warning
      annotations:
        description: The PersistentVolume claimed by {{ $labels.persistentvolumeclaim }} in Namespace {{ $labels.namespace }} only has {{ $value | humanizePercentage }} free inodes.
        summary: PersistentVolumeInodes are filling up.
