kind: PrometheusRule
apiVersion: monitoring.coreos.com/v1
metadata:
  name: kube-high-kube-network-latency-spike
  namespace: messaging
spec:
  groups:
  - name: kube-node-alerts
    rules:
    - alert: KubeHighNetworkLatencySpike
      expr: histogram_quantile(0.95, sum(rate(kubelet_http_requests_duration_seconds_bucket{le="1"}[2m])) by (job, path, handler)) / histogram_quantile(0.95, sum(rate(kubelet_http_requests_duration_seconds_bucket{le="1"}[10m])) by (job, path, handler)) > 1.5
      for: 2m
      labels:
        severity: warning
        interface: "{{ $labels.interface }}"
      annotations:
        summary: "Sudden kubelet latency increase ({{ $labels.job }} - {{ $labels.path }} - {{ $labels.handler }})"
        description: "95th percentile kubelet request latency has increased by more than 50% over the last 2 minutes. Investigate potential network, kubelet, or API server issues."
