kind: PrometheusRule
apiVersion: monitoring.coreos.com/v1
metadata:
  name: kube-network-traffic-saturation-receive-critical
  namespace: messaging
spec:
  groups:
  - name: kube-node-alerts
    rules:
    - alert: KubeNetworkTrafficSaturationReceiveCritical
      expr: sum by (pod) (rate(node_network_receive_bytes_total[2m])) / sum by (pod) (node_cpu_seconds_total{mode="system"}) * 100 > 80
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Critical network errors on node {{ $labels.pod }}"
        description: "Network interface on {{ $labels.pod }} is experiencing alarming errors. Investigation required - near critical threshold."

---
kind: PrometheusRule
apiVersion: monitoring.coreos.com/v1
metadata:
  name: kube-network-traffic-saturation-receive-warning
spec:
  groups:
  - name: kube-node-alerts
    rules:
    - alert: KubeNetworkTrafficSaturationReceiveWarning
      expr: sum by (pod) (rate(node_network_receive_bytes_total[2m])) / sum by (pod) (node_cpu_seconds_total{mode="system"}) * 100 > 70
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Network receive traffic saturation approaching warning threshold on node {{ $labels.pod }}"
        description: "Network receive traffic on node {{ $labels.pod }} is approaching the warning threshold (over 70% of CPU capacity). Investigate for potential bottlenecks."
