kind: PrometheusRule
apiVersion: monitoring.coreos.com/v1
metadata:
  name: kube-container-waiting
  namespace: messaging
spec:
  groups:
  - name: kube-node-alerts
    rules:
    - alert: KubeContainerWaiting
      expr: |
        sum by (namespace, pod, container, cluster) (kube_pod_container_status_waiting_reason{job="kube-state-metrics"}) > 0
      for: 1h
      labels:
        severity: warning
      annotations:
        description: pod/{{ $labels.pod }} in namespace {{ $labels.namespace }} on container {{ $labels.container}} has been in waiting state for longer than 1 hour.
        summary: Pod container waiting longer than 1 hour.
