kind: PrometheusRule
apiVersion: monitoring.coreos.com/v1
metadata:
  name: kube-job-slow-completion
  namespace: messaging
spec:
  groups:
  - name: kube-node-alerts
    rules:
    - alert: KubeJobSlowCompletion
      expr: kube_job_spec_completions - kube_job_status_succeeded - kube_job_status_failed > 0
      for: 12h
      labels:
        severity: critical
      annotations:
        description: "Kubernetes Job {{ $labels.namespace }}/{{ $labels.job_name }} did not complete in time.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
        summary: Kubernetes Job slow completion (instance {{ $labels.instance }})
