kind: PrometheusRule
apiVersion: monitoring.coreos.com/v1
metadata:
  name: kube-stateful-set-replicas-mismatch
  namespace: messaging
spec:
  groups:
  - name: kube-node-alerts
    rules:
    - alert: KubeStatefulSetReplicasMismatch
      expr: |
        (
        kube_statefulset_status_replicas_ready{job="kube-state-metrics"}
        !=
        kube_statefulset_status_replicas{job="kube-state-metrics"}
        ) and (
        changes(kube_statefulset_status_replicas_updated{job="kube-state-metrics"}[10m])
        == 0)
      for: 15m
      labels:
        severity: warning
      annotations:
        description: StatefulSet {{ $labels.namespace }}/{{ $labels.statefulset }} has not matched the expected number of replicas for longer than 15 minutes.
        summary: StatefulSet has not matched the expected number of replicas.
