kind: PrometheusRule
apiVersion: monitoring.coreos.com/v1
metadata:
  name: kube-memory-over-commit
  namespace: messaging
spec:
  groups:
  - name: kube-node-alerts
    rules:
    - alert: KubeMemoryOvercommit
      expr: |
        sum(namespace_memory:kube_pod_container_resource_requests:sum{}) - (sum(kube_node_status_allocatable{resource="memory", job="kube-state-metrics"}) - max(kube_node_status_allocatable{resource="memory", job="kube-state-metrics"})) > 0
        and
        (sum(kube_node_status_allocatable{resource="memory", job="kube-state-metrics"}) - max(kube_node_status_allocatable{resource="memory", job="kube-state-metrics"})) > 0
      for: 10m
      labels:
        severity: warning
      annotations:
        description: Cluster has overcommitted memory resource requests for Pods by {{ $value humanize }} bytes and cannot tolerate node failure.
        summary: Cluster has overcommitted memory resource requests.
