{
 "title": "Rabbit GCP app metrics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "logback_events_total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "logback_events_total", "legendFormat": "{{level}}" }
   ]
  },
  {
   "title": "acknowledged published messages total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_acknowledged_published_total",
     "legendFormat": "pod"
    }
   ]
  },
  {
   "title": "Disk free (/pushmepullyou/*)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "disk_free_bytes", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "system_cpu_usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_cpu_usage" }
   ]
  },
  {
   "title": "rabbitmq_failed_to_publish_total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_failed_to_publish_total"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_uptime_seconds" }
   ]
  },
  {
   "title": "executor_pool_core_threads",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "executor_pool_core_threads", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "executor_queued_tasks",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "executor_queued_tasks", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "rabbitmq_rejected_total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rabbitmq_rejected_total" }
   ]
  },
  {
   "title": "system_load_average_1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    { "expr": "system_load_average_1m", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "produceMsg_exceptions_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    { "expr": "produceMsg_exceptions_total", "legendFormat": "{{queue}}" }
   ]
  },
  {
   "title": "spring_integration_send_seconds_max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "spring_integration_send_seconds_max{}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "rabbitmq_channels",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rabbitmq_channels{container=\"rabbit-gcp\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "produceMsg_nacks_total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "targets": [
    { "expr": "produceMsg_nacks_total" }
   ]
  },
  {
   "title": "produceMsg_attempts_total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "targets": [
    { "expr": "produceMsg_attempts_total", "legendFormat": "queue: {{queue}}" }
   ]
  }
 ]
}