apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rabbitmq-high-message-acknowledgement-latency
  namespace: messaging
  labels:
    role: alert-rules
spec:
  groups:
  - name: rabbitmq
    rules:
    - alert: RabbitMQHighMessageAcknowledgementLatency
      expr: avg(rate(rabbitmq_global_messages_acknowledged_total[5m])) > 0.5
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High RabbitMQ Message Acknowledgement Latency"
        description: "The average message acknowledgement latency on RabbitMQ is above 0.5 messages per second for the last 5 minutes. This could indicate potential issues with message processing or resource constraints."
