{
 "title": "RabbitMQ / Queue Overview - FINAL",
 "tags": [
  "rabbitmq",
  "rabbitmq-mixin"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(rabbitmq_identity_info, namespace)"
    }
   },
   {
    "name": "rabbitmq_cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(rabbitmq_identity_info{namespace=\"$namespace\"},rabbitmq_cluster)"
    }
   },
   {
    "name": "vhost",
    "label": "Virtual Host",
    "query": {
     "query": "label_values(rabbitmq_detailed_queue_messages,vhost)"
    }
   },
   {
    "name": "queue",
    "label": "Queue",
    "query": {
     "query": "rabbitmq_detailed_queue_messages"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Messages Ready Per Queue",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(queue) (rabbitmq_detailed_queue_messages{queue=\"$queue\"})"
    }
   ]
  },
  {
   "title": "Total Queues",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_queues * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Incoming messages / s",
   "type": "stat",
   "description": "rabbitmq_global_messages_received_total",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(queue) (rate(rabbitmq_channel_messages_delivered_ack_total[1m]))"
    }
   ]
  },
  {
   "title": "Outgoing messages / s",
   "type": "stat",
   "description": "rabbitmq_channel_messages_delivered_ack_total",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(queue) (rate(rabbitmq_channel_messages_delivered_ack_total[1m]))"
    }
   ]
  },
  {
   "title": "Queues with Messages Unacked",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(rabbitmq_queue_messages_unacked{vhost=~\"$vhost\"}\n* on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=~\"$rabbitmq_cluster\", namespace=\"$namespace\"} > 0)\n"
    }
   ]
  },
  {
   "title": "Queues with Messages Ready",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(rabbitmq_queue_messages_ready{vhost=~\"$vhost\"}\n* on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=~\"$rabbitmq_cluster\", namespace=\"$namespace\"} > 0)\n"
    }
   ]
  },
  {
   "title": "Consumers Per Queue",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(queue) (rabbitmq_detailed_queue_consumers{queue=\"$queue\"})"
    }
   ]
  },
  {
   "title": "Total Connections",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_connections * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Total Publishers",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_channels * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"}) - sum(rabbitmq_channel_consumers * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Total Nodes",
   "type": "gauge",
   "description": "Per rabbit cluster",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_build_info * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Memory Usage Per Queue",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(queue) (rate(rabbitmq_detailed_queue_process_memory_bytes{queue=\"$queue\"}[5m]))",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Queue RAM usage",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(queue) (rabbitmq_detailed_queue_process_memory_bytes{queue=\"$queue\"})",
     "legendFormat": "{{pod}}:{{queue}}"
    }
   ]
  },
  {
   "title": "Messages in Queue",
   "type": "stat",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_detailed_queue_messages",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Messages / Queue",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rabbitmq_detailed_queue_messages",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Virtual Host Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Virtual Host Ready & Unacked Messages",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    rabbitmq_detailed_queue_messages_ready{namespace=\"$namespace\", vhost=~\"$vhost\"}[$__rate_interval]\n  )\n) by (instance, vhost)\n* on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=~\"$rabbitmq_cluster\", namespace=\"$namespace\"}\n",
     "legendFormat": "Ready - {{ vhost }}"
    },
    {
     "expr": "sum(\n  increase(\n    rabbitmq_detailed_queue_messages_unacked{namespace=\"$namespace\", vhost=~\"$vhost\"}[$__rate_interval]\n  )\n) by (instance, vhost)\n* on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=~\"$rabbitmq_cluster\", namespace=\"$namespace\"}\n",
     "legendFormat": "Unacked - {{ vhost }}"
    }
   ]
  },
  {
   "title": "Queue Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Queue Length & Consumers",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum by (instance, vhost, queue) (rabbitmq_detailed_queue_consumers{vhost=~\"$vhost\", namespace=\"$namespace\", queue=~\"$queue\"})\n* on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=~\"$rabbitmq_cluster\", namespace=\"$namespace\"}\n"
    },
    {
     "expr": "sum by (instance, vhost, queue) (rabbitmq_detailed_queue_consumers{vhost=~\"$vhost\", namespace=\"$namespace\", queue=~\"$queue\"})\n* on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=~\"$rabbitmq_cluster\", namespace=\"$namespace\"}\n"
    }
   ]
  },
  {
   "title": "Queue Ready & Unacked Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    rabbitmq_detailed_queue_messages_ready{namespace=\"$namespace\", vhost=~\"$vhost\", queue=~\"$queue\"}[$__rate_interval]\n  )\n) by (instance, vhost, queue)\n* on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=~\"$rabbitmq_cluster\", namespace=\"$namespace\"}\n",
     "legendFormat": "Ready - {{ queue }}/{{ vhost }}"
    },
    {
     "expr": "sum(\n  increase(\n    rabbitmq_detailed_queue_messages_unacked{namespace=\"$namespace\", vhost=~\"$vhost\", queue=~\"$queue\"}[$__rate_interval]\n  )\n) by (instance, vhost, queue)\n* on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=~\"$rabbitmq_cluster\", namespace=\"$namespace\"}\n",
     "legendFormat": "Unacked - {{ queue }}/{{ vhost }}"
    }
   ]
  }
 ]
}